### PR TITLE
fix: update scalar to v1.13.0

### PR DESCRIPTION
**Pull request by marclave**
lot's of great fixes in v1.13.0!

```
97cd84e9: feat: client ignore list
5dac9c51: fix: open section on search result click
0e0f34b3: fix: cleanup safari bugs
7582e82a: fix: classic layout stylings
d5d55407: feat: expose dark mode light mode property in config
7d502131: fix: add markdown rendering for body schema
3e7c4cf7: feat: add fetch examples
859977f8: feat: Add dynamic content type selection for request body
0b66933d: fix: declare theme font for buttons and fix regressed font weight
87ed7f01: fix: markdown second level margin issue
4513c725: feat: add intro flare for gradients
```

### CODE REVIEW

**Comment by kravetsone** [comment]
@marclave 
maybe add something like "latest" version by default?

**Comment by marclave** [comment]
That would be amazing to keep it always at default, then we can override it if a user specifies a version ✨

I'll do this and make a new PR

**Comment by jmcudd** [comment]
@marclave Can we get #95 in on this?

**Comment by marclave** [comment]
yes we certainly can ✨ , let me polish up that PR right now!

**Comment by marclave** [comment]
@kravetsone @jmcudd added both feedback to this PR :) 

now we:
1. default to use latest (much better)
2. add optional override scalarCDN parameter :)

**Pull request merged**
