### PR TITLE
Update scalar configuration

### PR DESCRIPTION
**Pull request by zAlweNy26**
I saw that the `api-reference` package from scalar was a bit old and not really used by the plugin.
I also modified a bit the `ScalarRender` method to use the OpenAPI information object so that is now possible to modify the title of the page.
I hope you like it :)

### CODE REVIEW

**Comment by marclave** [comment]
hey @zAlweNy26 ! love this : )

sorry it took me so long to get to this, but if you wanna update the conflicts we can defs get this in!

**Comment by zAlweNy26** [comment]
Hi, I'll resolve the conflicts as soon as possible :)

**Comment by zAlweNy26** [comment]
@marclave everything should be ok now 👍🏽

**Review by marclave — APPROVED** [review]

**Comment by zAlweNy26** [comment]
@marclave I see there is a new conflict, do you want me to resolve it?

**Comment by marclave** [comment]
@zAlweNy26 omg im so sorry, yes!

**Comment by zAlweNy26** [comment]
@marclave done, it can be merged now :)

**Comment by vastamaki** [comment]
Any estimates when this will be released? This is quite critical plugin for the projects I am working with and we kinda suffer from that this is not up to date. Many of the issues/new features are already fixed/implemented in Scalar. I definitely can help maintaining this as well if you happen to need help :-)

**Pull request merged**
